[platformio]
# 将源码目录重定向到固件目录
src_dir = firmware/plant_node/src

[env:esp32s3mini]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

# 引入 Python 脚本，路径需要加上相对路径
extra_scripts = pre:firmware/plant_node/inject_config.py

lib_deps =
    knolleary/PubSubClient
    bblanchon/ArduinoJson
    adafruit/Adafruit AHTX0
    adafruit/Adafruit BMP280 Library
